{% set version = "3.3-1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spatstat.linnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.linnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.linnet/spatstat.linnet_{{ version }}.tar.gz
  sha256: deca866a2db895d137bbf7fceb35bc12df80bb82972da45e1ff90b9c354092ab

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-spatstat.data              # [build_platform != target_platform]
    - r-spatstat.explore           # [build_platform != target_platform]
    - r-spatstat.geom              # [build_platform != target_platform]
    - r-spatstat.model             # [build_platform != target_platform]
    - r-spatstat.random            # [build_platform != target_platform]
    - r-spatstat.sparse            # [build_platform != target_platform]
    - r-spatstat.univar            # [build_platform != target_platform]
    - r-spatstat.utils            # [build_platform != target_platform]
  host:
    - r-base
    - r-matrix
    - r-spatstat.data >=3.1_4
    - r-spatstat.explore >=3.4_3
    - r-spatstat.geom >=3.4_1
    - r-spatstat.model >=3.3_5
    - r-spatstat.random >=3.4_1
    - r-spatstat.sparse >=3.1_0
    - r-spatstat.univar >=3.1_3
    - r-spatstat.utils >=3.1_4
  run:
    - r-base
    - r-matrix
    - r-spatstat.data >=3.1_4
    - r-spatstat.explore >=3.4_3
    - r-spatstat.geom >=3.4_1
    - r-spatstat.model >=3.3_5
    - r-spatstat.random >=3.4_1
    - r-spatstat.sparse >=3.1_0
    - r-spatstat.univar >=3.1_3
    - r-spatstat.utils >=3.1_4

test:
  commands:
    - $R -e "library('spatstat.linnet')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.linnet')\""  # [win]

about:
  home: http://spatstat.org/
  dev_url: https://github.com/spatstat/spatstat.linnet
  license: GPL-2.0-or-later
  summary: This is a subset of the 'spatstat' package, containing its functionality for spatial data on a linear network.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: spatstat.linnet
# Version: 1.65-3
# Date: 2021-01-30
# Title: Linear Networks Functionality of the 'spatstat' Package
# Authors@R: c(person("Adrian", "Baddeley", role = c("aut", "cre"), email = "Adrian.Baddeley@curtin.edu.au"), person("Rolf", "Turner", role = "aut", email="r.turner@auckland.ac.nz"), person("Ege",   "Rubak", role = "aut", email = "rubak@math.aau.dk"), person("Ottmar", "Cronie", role = "ctb"), person("Tilman", "Davies", role = "ctb"), person("Greg", "McSwiggan", role = "ctb"), person("Suman", "Rakshit", role = "ctb"))
# Maintainer: Adrian Baddeley <Adrian.Baddeley@curtin.edu.au>
# Depends: R (>= 3.5.0), spatstat.data (>= 1.4-2), spatstat.geom (>= 1.65-0), spatstat.core (>= 1.65-0), stats, graphics, grDevices, methods, utils
# Imports: spatstat.utils (>= 1.17-0), Matrix
# Suggests:
# Description: This is a subset of the 'spatstat' package, containing its functionality for spatial data on a linear network.
# License: GPL (>= 2)
# URL: http://spatstat.org/
# LazyData: true
# NeedsCompilation: yes
# ByteCompile: true
# BugReports: https://github.com/baddstats/spatstat.linnet/issues
# Packaged: 2021-01-30 11:11:15 UTC; adrian
# Author: Adrian Baddeley [aut, cre], Rolf Turner [aut], Ege Rubak [aut], Ottmar Cronie [ctb], Tilman Davies [ctb], Greg McSwiggan [ctb], Suman Rakshit [ctb]
# Repository: CRAN
# Date/Publication: 2021-02-05 09:40:11 UTC
